#ifndef HEADER_H
#define HEADER_H

#include <iostream>
#include <conio.h>
#include <stdlib.h>
#include <string>
#include <stdio.h>
#include <math.h>
#include <windows.h>

void E1(void);
void E2(void);
void E3(void);
void E4(void);
void E5(void);
void E6(void);
void E7(void);
void E8(void);
void E9(void);
void E10(void);
void E11(void);
void E12(void);
void E13(void);
void E14(void);
void E15(void);
void E16(void);
void E17(void);
void E18(void);
void E19(void);
void E20(void);
void E21(void);
void E22(void);
void E23(void);
void E24(void);
void E25(void);
void E26(void);
void E27(void);
void E28(void);
void E29(void);
void E30(void);
void E31(void);
void E32(void);
void E33(void);
void E34(void);
void E35(void);
#endif
